// automatically generated by the FlatBuffers compiler, do not modify
/**
 * Enum for the mode of data (real, simulated, synthetic)
 */
export var DataMode;
(function (DataMode) {
    DataMode[DataMode["real"] = 0] = "real";
    DataMode[DataMode["simulated"] = 1] = "simulated";
    DataMode[DataMode["synthetic"] = 2] = "synthetic";
})(DataMode || (DataMode = {}));
