// automatically generated by the FlatBuffers compiler, do not modify
/**
 * Enum for the type of site
 */
export var SiteType;
(function (SiteType) {
    SiteType[SiteType["LAUNCH_SITE"] = 0] = "LAUNCH_SITE";
    SiteType[SiteType["OBSERVATION_STATION"] = 1] = "OBSERVATION_STATION";
    SiteType[SiteType["RESEARCH_FACILITY"] = 2] = "RESEARCH_FACILITY";
    SiteType[SiteType["SATELLITE_GROUND_STATION"] = 3] = "SATELLITE_GROUND_STATION";
    SiteType[SiteType["SPACEPORT"] = 4] = "SPACEPORT";
    SiteType[SiteType["MILITARY_BASE"] = 5] = "MILITARY_BASE";
    SiteType[SiteType["WEATHER_STATION"] = 6] = "WEATHER_STATION";
    SiteType[SiteType["ASTRONOMICAL_OBSERVATORY"] = 7] = "ASTRONOMICAL_OBSERVATORY";
    SiteType[SiteType["EDUCATIONAL_INSTITUTE"] = 8] = "EDUCATIONAL_INSTITUTE";
    SiteType[SiteType["COMMUNICATION_HUB"] = 9] = "COMMUNICATION_HUB";
    SiteType[SiteType["POWER_PLANT"] = 10] = "POWER_PLANT";
    SiteType[SiteType["INDUSTRIAL_COMPLEX"] = 11] = "INDUSTRIAL_COMPLEX";
    SiteType[SiteType["TRANSPORTATION_HUB"] = 12] = "TRANSPORTATION_HUB";
    SiteType[SiteType["URBAN_AREA"] = 13] = "URBAN_AREA";
    SiteType[SiteType["NATIONAL_PARK"] = 14] = "NATIONAL_PARK";
    SiteType[SiteType["HISTORICAL_SITE"] = 15] = "HISTORICAL_SITE";
    SiteType[SiteType["OTHER"] = 16] = "OTHER";
})(SiteType || (SiteType = {}));
