// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Emitter } from './Emitter.js';


export class EmitterCollection {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EmitterCollection {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEmitterCollection(bb:flatbuffers.ByteBuffer, obj?:EmitterCollection):EmitterCollection {
  return (obj || new EmitterCollection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEmitterCollection(bb:flatbuffers.ByteBuffer, obj?:EmitterCollection):EmitterCollection {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EmitterCollection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

EMITTERS(index: number, obj?:Emitter):Emitter|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Emitter()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

emittersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startEmitterCollection(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addEmitters(builder:flatbuffers.Builder, EMITTERSOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, EMITTERSOffset, 0);
}

static createEmittersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEmittersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endEmitterCollection(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEmitterCollection(builder:flatbuffers.Builder, EMITTERSOffset:flatbuffers.Offset):flatbuffers.Offset {
  EmitterCollection.startEmitterCollection(builder);
  EmitterCollection.addEmitters(builder, EMITTERSOffset);
  return EmitterCollection.endEmitterCollection(builder);
}
}
