// TODO: Add the aperture size of telescopes as an optional parameter

export const Operators = {
    USSF: 'USSF',
    USA: 'US ARMY',
    RAF: 'RAF',
    UKSA: 'UKSA',
    RAAF: 'RAAF',
    ESA: 'ESA',
    ROC: 'ROC',
    EISCAT: 'EISCAT',
    RUSSF: 'RUS SF', //Russian Space Forces
    MIT: 'MIT',
    NOR: 'NOR',
    PLA: 'PLA',
    CAS: 'CAS',
    LEOLABS: 'LEO LABS',
    CALTECH: 'CALTECH',
    COMMERCIAL: 'COMMERCIAL',
    ITAF: 'ITAF', // Italian Air Force
}

export const sensors = {
    CODSFS: {
        objName: 'CODSFS',
        shortName: 'COD',
        id: 0,
        name: 'Cape Cod SFS',
        uiName: 'Cape Cod SFS',
        system: 'PAVE PAWS UEWR',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 41.754785,
        lon: -70.539151,
        alt: 0.060966,
        obsminaz: 347,
        obsmaxaz: 227,
        obsminel: 3,
        obsmaxel: 85,
        obsminrange: 200,
        obsmaxrange: 5556,
        changeObjectInterval: 1000,
        beamwidth: 2.0, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
        linkAehf: true,
        linkWgs: true,
        url: 'https://www.radartutorial.eu/19.kartei/01.oth/karte004.en.html',
        country: 'United States',
        operator: Operators.USSF,
        staticNum: 0, // For Testing Only
    },
    BLEAFB: {
        objName: 'BLEAFB',
        shortName: 'BLE',
        id: 0,
        name: 'Beale AFB',
        uiName: 'Beale AFB',
        system: 'PAVE PAWS UEWR',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 39.136064,
        lon: -121.351237,
        alt: 0.112, // Open Street Maps
        obsminaz: 126,
        obsmaxaz: 6,
        obsminel: 3,
        obsmaxel: 85,
        obsminrange: 200,
        obsmaxrange: 5556,
        changeObjectInterval: 1000,
        beamwidth: 2.0, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
        linkAehf: true,
        linkWgs: true,
        country: 'United States',
        operator: Operators.USSF,
    },
    CLRSFS: {
        objName: 'CLRSFS',
        shortName: 'CLR',
        id: 0,
        name: 'Clear SFS',
        uiName: 'Clear SFS',
        system: 'PAVE PAWS UEWR',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 64.290556,
        lon: -149.186944,
        alt: 0.175, // Open Street Maps
        obsminaz: 184,
        obsmaxaz: 64,
        obsminel: 3,
        obsmaxel: 85,
        obsminrange: 200,
        obsmaxrange: 5556,
        changeObjectInterval: 1000,
        beamwidth: 2.0, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
        linkAehf: true,
        linkWgs: true,

        country: 'United States',
        operator: Operators.USSF,
    },
    EGLAFB: {
        objName: 'EGLAFB',
        shortName: 'EGL',
        id: 0,
        name: 'Eglin AFB',
        uiName: 'Eglin AFB',
        system: 'AN/FPS-85',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 30.572411,
        lon: -86.214836,
        alt: 0.039, // Open Street Maps
        obsminaz: 120,
        obsmaxaz: 240,
        obsminel: 3,
        obsmaxel: 105,
        obsminrange: 200,
        obsmaxrange: 200000,
        changeObjectInterval: 1000,
        beamwidth: 1.4, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
        url: 'https://www.radartutorial.eu/19.kartei/01.oth/karte002.en.html',
        country: 'United States',
        operator: Operators.USSF,
    },
    RAFFYL: {
        objName: 'RAFFYL',
        shortName: 'FYL',
        id: 0,
        name: 'RAF Fylingdales',
        uiName: 'RAF Fylingdales',
        system: 'BMEWS UEWR',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 54.361758,
        lon: -0.670051,
        alt: 0.26, // Open Street Maps
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 3,
        obsmaxel: 85,
        obsminrange: 200,
        obsmaxrange: 5556,
        changeObjectInterval: 1000,
        beamwidth: 2.0, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
        linkAehf: true,
        linkWgs: true,
        country: 'United Kingdom',
        operator: Operators.RAF,
    },
    CAVSFS: {
        objName: 'CAVSFS',
        shortName: 'CAV',
        id: 0,
        name: 'Cavalier SFS',
        uiName: 'Cavalier SFS',
        system: 'PARCS',
        type: "PHASED_ARRAY_RADAR",
        lat: 48.724567,
        lon: -97.899755,
        alt: 0.352, // Open Street Maps
        obsminaz: 298,
        obsmaxaz: 78,
        obsminel: 1.9,
        obsmaxel: 95,
        obsminrange: 200,
        obsmaxrange: 3300, // 1,780 Nm http://www.fortwiki.com/Cavalier_Air_Force_Station
        changeObjectInterval: 1000,
        beamwidth: 1.2, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
        linkAehf: true,

        url: 'https://mostlymissiledefense.com/2012/04/12/parcs-cavalier-radar-april-12-2012/',
        country: 'United States',
        volume: true,
        operator: Operators.USSF,
    },
    PITSB: {
        objName: 'PITSB',
        shortName: 'THL',
        id: 0,
        name: 'Pituffik SB',
        uiName: 'Pituffik SB',
        system: 'BMEWS UEWR',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 76.570322,
        lon: -68.299211,
        alt: 0.392, // Open Street Maps
        obsminaz: 297,
        obsmaxaz: 177,
        obsminel: 3,
        obsmaxel: 85,
        obsminrange: 200,
        obsmaxrange: 5556,
        changeObjectInterval: 1000,
        beamwidth: 2.0, // National Research Council 1979. Radiation Intensity of the PAVE PAWS Radar System. Washington, DC: The National Academies Press.
        linkAehf: true,
        linkWgs: true,
        url: 'https://www.radartutorial.eu/19.kartei/01.oth/karte004.en.html',
        country: 'United States',
        operator: Operators.USSF,
    },
    COBRADANE: {
        objName: 'COBRADANE',
        shortName: 'CDN',
        id: 0,
        name: 'Eareckson Air Station',
        uiName: 'Eareckson AFS',
        system: 'COBRA DANE',
        band: 'L-Band',
        type: "PHASED_ARRAY_RADAR",
        lat: 52.737,
        lon: 174.092,
        alt: 0.066, // Open Street Maps
        // boresight 319az https://mostlymissiledefense.com/2012/04/12/cobra-dane-radar-april-12-2012/
        obsminaz: 259, // https://www.radartutorial.eu/19.kartei/01.oth/karte003.en.html
        obsmaxaz: 19,
        obsminel: 2,
        obsmaxel: 30,
        obsminrange: 200,
        obsmaxrange: 14000, // https://mostlymissiledefense.com/2012/04/12/cobra-dane-radar-april-12-2012/
        obsminaz2: 251,
        obsmaxaz2: 27,
        obsminel2: 30,
        obsmaxel2: 80,
        obsminrange2: 200,
        obsmaxrange2: 14000,
        changeObjectInterval: 1000,
        beamwidth: 0.6, // https://www.radartutorial.eu/19.kartei/01.oth/karte003.en.html
        linkWgs: true,
        url: 'https://www.radartutorial.eu/19.kartei/01.oth/karte004.en.html',
        country: 'United States',
        volume: true,
        operator: Operators.USSF,
    },
    KWAJALT: {
        objName: 'KWAJALT',
        shortName: 'ALT',
        id: 0,
        name: 'ALTAIR',
        uiName: 'Kwajalein Atoll',
        system: 'ALTAIR',
        band: 'VHF/UHF',
        type: "MECHANICAL",
        lat: 8.716667,
        lon: 167.733333,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 1,
        obsmaxel: 90,
        obsminrange: 200,
        obsmaxrange: 200000,
        changeObjectInterval: 20000,
        linkAehf: true,
        linkWgs: true,
        url: 'https://www.radartutorial.eu/19.kartei/01.oth/karte005.en.html',
        country: 'United States',
        operator: Operators.USA,
    },
    KWAJGBRP: {
        objName: 'KWAJGBRP',
        id: 0,
        name: 'Ground-Based Radar Prototype (GBR-P)',
        uiName: 'Kwajalein Atoll',
        system: 'GBR-P',
        band: 'X-Band',
        type: "MECHANICAL",
        lat: 8.716668,
        lon: 167.773334,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 1,
        obsmaxel: 90,
        obsminrange: 200,
        obsmaxrange: 200000,
        changeObjectInterval: 20000,
        url: '',
        country: 'United States',
        operator: Operators.USA,
    },
    KWAJMMW: {
        objName: 'KWAJMMW',
        id: 0,
        name: 'Millimeter Wave Radar',
        uiName: 'Kwajalein Atoll',
        system: 'Millimeter Wave Radar',
        type: "MECHANICAL",
        lat: 8.756668,
        lon: 167.773334,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 1,
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 2500,
        changeObjectInterval: 20000,
        url: '',
        country: 'United States',
        operator: Operators.USA,
    },
    KWAJALC: {
        objName: 'KWAJALC',
        id: 0,
        name: 'ALCOR Radar',
        uiName: 'Kwajalein Atoll',
        system: 'ALCOR',
        band: 'C-Band',
        type: "MECHANICAL",
        lat: 8.716668,
        lon: 167.773334,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 1,
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 2300,

        changeObjectInterval: 20000,

        url: '',
        country: 'United States',
        operator: Operators.USA,
    },
    KWAJTDX: {
        objName: 'KWAJTDX',
        id: 0,
        name: 'TRADEX Radar',
        uiName: 'Kwajalein Atoll',
        system: 'TRADEX',
        type: "MECHANICAL",
        lat: 8.756668,
        lon: 167.733334,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 1,
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,

        url: '',
        country: 'United States',
        operator: Operators.USA,
    },
    KWAJSPF: {
        objName: 'KWAJSPF',
        shortName: 'SF',
        id: 0,
        name: 'Space Fence',
        uiName: 'Kwajalein Atoll',
        system: 'Space Fence',
        band: 'S-Band',
        type: "PHASED_ARRAY_RADAR",
        lat: 8.723, // SDC7-paper1014.pdf
        lon: 167.719,
        alt: 0.007,
        obsminaz: 268, // TODO This needs a better system (same as LEO Labs)
        obsmaxaz: 272,
        obsminel: 5, // ??
        obsmaxel: 175, // ??
        obsminrange: 50,
        obsmaxrange: 3057.754, // https://www.spaceforce.mil/News/Article/2142648/swinging-for-the-space-fence/

        changeObjectInterval: 2000,

        url: '',
        country: 'United States',
        operator: Operators.USSF,
    },
    MITMIL: {
        objName: 'MITMIL',
        shortName: 'MIL',
        id: 0,
        name: 'Westford',
        uiName: 'Westford',
        system: 'Millstone',
        type: "MECHANICAL",
        lat: 42.6233,
        lon: -71.4882,
        alt: 0.131,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 1,
        obsmaxel: 90,
        obsminrange: 200,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        url: 'https://mostlymissiledefense.com/2012/05/05/space-surveillance-sensors-millstone-hill-radar/',
        country: 'United States',
        operator: Operators.MIT,
    },
    GEODDSDGC: {
        objName: 'GEODDSDGC',
        id: 0,
        name: 'Diego Garcia',
        uiName: 'Diego Garcia',
        system: 'GEODSS',
        type: "OPTICAL",
        lat: -7.29648,
        lon: 72.390153,
        alt: 0.0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 20, // https://www.osti.gov/servlets/purl/1253293
        obsmaxel: 90,
        obsminrange: 15000,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        url: 'https://mostlymissiledefense.com/2012/08/20/space-surveillance-sensors-geodss-ground-based-electro-optical-deep-space-surveillance-system-august-20-2012/',
        country: 'United States',
        operator: Operators.USSF,
    },
    GEODDSMAU: {
        objName: 'GEODDSMAU',
        id: 0,
        name: 'Maui',
        uiName: 'Maui',
        system: 'GEODSS',
        type: "OPTICAL",
        lat: 20.70835,
        lon: -156.257595,
        alt: 3.0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 20, // https://www.osti.gov/servlets/purl/1253293
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        url: 'https://mostlymissiledefense.com/2012/08/20/space-surveillance-sensors-geodss-ground-based-electro-optical-deep-space-surveillance-system-august-20-2012/',
        country: 'United States',
        operator: Operators.USSF,
    },
    GEODDSSOC: {
        objName: 'GEODDSSOC',
        id: 0,
        name: 'Socorro',
        uiName: 'Socorro',
        system: 'GEODSS',
        type: "OPTICAL",
        lat: 33.817233,
        lon: -106.659961,
        alt: 1.24,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 20, // https://www.osti.gov/servlets/purl/1253293
        obsmaxel: 90,
        obsminrange: 15000,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        url: 'https://mostlymissiledefense.com/2012/08/20/space-surveillance-sensors-geodss-ground-based-electro-optical-deep-space-surveillance-system-august-20-2012/',
        country: 'United States',
        operator: Operators.USSF,
    },
    RAFASC: {
        objName: 'RAFASC',
        shortName: 'ASC',
        id: 0,
        name: 'Ascension Island',
        uiName: 'RAF Ascension Island',
        system: 'FPQ-15',
        band: 'C-Band',
        type: "MECHANICAL",
        lat: -7.969444,
        lon: -14.393889,
        alt: 0.0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 1,
        obsmaxel: 90,
        obsminrange: 200,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        url: '',
        country: 'United States',
        operator: Operators.USSF,
    },
    GLBII: {
        objName: 'GLBII',
        id: 0,
        name: 'Vardø',
        uiName: 'Vardø',
        system: 'Globus II',
        type: "MECHANICAL",
        lat: 70.3671,
        lon: 31.1271,
        alt: 0.0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 1,
        obsmaxel: 90,
        obsminrange: 200,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        url: '',
        country: 'Norway',
        operator: Operators.NOR,
    },
    HOLCBAND: {
        objName: 'HOLCBAND',
        id: 0,
        name: 'Holt Naval Communication Station',
        uiName: 'Holt Naval CS',
        system: 'C-Band',
        band: 'C-Band',
        type: "MECHANICAL",
        lat: -21.816195,
        lon: 114.165637,
        alt: 0.0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 1,
        obsmaxel: 90,
        obsminrange: 200,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        url: '',
        country: 'Australia',
        operator: Operators.RAAF,
    },
    HOLSST: {
        objName: 'HOLSST',
        id: 0,
        name: 'Holt Naval Communication Station',
        uiName: 'Holt Naval CS',
        system: 'SST',
        type: "OPTICAL",
        lat: -21.816195,
        lon: 114.165637,
        alt: 0.04572, // https://www.osti.gov/servlets/purl/1253293
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 20, // https://amostech.com/TechnicalPapers/2015/SSA/Graham.pdf
        obsmaxel: 90,
        obsminrange: 15000,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        url: '',
        country: 'Australia',
        operator: Operators.RAAF,
    },
    // //////////////
    // TPY-2 RADARS
    // //////////////
    HARTPY: {
        objName: 'HARTPY',
        id: 0,
        name: 'Har Keren TPY-2',
        uiName: 'Har Keren',
        system: 'TPY-2',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 30.995807,
        lon: 34.496062,
        alt: 0.173,
        obsminaz: 5,
        obsmaxaz: 125,
        obsminel: 5,
        obsmaxel: 95,
        obsminrange: 0,
        obsmaxrange: 3000, // https://missilethreat.csis.org/defsys/tpy-2/

        changeObjectInterval: 1000,
        url: '',
        country: 'United States',
        operator: Operators.USA,
    },
    QTRTPY: {
        objName: 'QTRTPY',
        id: 0,
        name: 'Al Udeid',
        uiName: 'Al Udeid',
        system: 'TPY-2',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 25.31598,
        lon: 51.146515,
        alt: 0.01,
        obsminaz: 335,
        obsmaxaz: 95,
        obsminel: 0,
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 3000, // https://missilethreat.csis.org/defsys/tpy-2/

        changeObjectInterval: 1000,
        url: '',
        country: 'United States',
        operator: Operators.USA,
    },
    KURTPY: {
        objName: 'KURTPY',
        id: 0,
        name: 'Kürecik Radar Station',
        uiName: 'Kürecik',
        system: 'TPY-2',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 38.349444,
        lon: 37.793611,
        alt: 1.969,
        obsminaz: 40,
        obsmaxaz: 160,
        obsminel: 0,
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 3000, // https://missilethreat.csis.org/defsys/tpy-2/

        changeObjectInterval: 1000,
        url: '',
        country: 'United States',
        operator: Operators.USA,
    },
    SHATPY: {
        objName: 'SHATPY',
        id: 0,
        name: 'Shariki Communication Site',
        uiName: 'Shariki',
        system: 'TPY-2',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 40.88809,
        lon: 140.337698,
        alt: 0.01,
        obsminaz: 230,
        obsmaxaz: 350,
        obsminel: 0,
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 3000, // https://missilethreat.csis.org/defsys/tpy-2/

        changeObjectInterval: 1000,
        url: '',
        country: 'United States',
        operator: Operators.USA,
    },
    KCSTPY: {
        objName: 'KCSTPY',
        id: 0,
        name: 'Kyogamisaki Communication Site',
        uiName: 'Kyogamisaki',
        system: 'TPY-2',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 35.766667,
        lon: 135.195278,
        alt: 0.01,
        obsminaz: 210,
        obsmaxaz: 330,
        obsminel: 0,
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 3000, // https://missilethreat.csis.org/defsys/tpy-2/

        changeObjectInterval: 1000,
        url: '',
        country: 'United States',
        operator: Operators.USA,
    },
    SBXRDR: {
        objName: 'SBXRDR',
        id: 0,
        name: 'Sea-Based X-Band Radar',
        uiName: 'Mobile (Ocean)',
        system: 'SBX',
        band: 'X-Band',
        type: "PHASED_ARRAY_RADAR",
        lat: 36.5012,
        lon: 169.6941,
        alt: 0.0,
        obsminaz: 275,
        obsmaxaz: 300,
        obsminel: 0,
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 4025,

        changeObjectInterval: 1000,
        url: '',
        country: 'United States',
        operator: Operators.USA,
    },
    // //////////////////////
    // LEO LABS
    // //////////////////////
    LEOMSR: {
        objName: 'LEOMSR',
        id: 0,
        name: 'Midland Space Radar',
        uiName: 'Midland Space Radar',
        system: 'UHF',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 31.9643,
        lon: -103.233245,
        alt: 0.855,
        obsminaz: 70,
        obsmaxaz: 72,
        obsminel: 30,
        obsmaxel: 91, // 91 to ensure visual overlap
        obsminrange: 100,
        obsmaxrange: 1800,
        obsminaz2: 250,
        obsmaxaz2: 252,
        obsminel2: 30,
        obsmaxel2: 91, // 91 to ensure visual overlap
        obsminrange2: 100,
        obsmaxrange2: 1800,

        changeObjectInterval: 1000,
        url: 'https://platform.leolabs.space/sites/msr',
        country: 'United States',
        volume: true,
        operator: Operators.LEOLABS,
    },

    LEOPFISR: {
        objName: 'LEOPFISR',
        id: 0,
        name: 'Poker Flat Incoherent Scatter Radar',
        uiName: 'Poker Flat ISR',
        system: 'Incoherent Scatter',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 65.12992,
        lon: -147.47104,
        alt: 0.23,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 45,
        obsmaxel: 90, // 91 to ensure visual overlap
        obsminrange: 100,
        obsmaxrange: 1800,

        changeObjectInterval: 1000,
        url: 'https://platform.leolabs.space/sites/pfisr',
        country: 'United States',
        // "boresight": { "azimuth": 15.0, "elevation": 74.0 },
        // "transmitFrequency": 450000000.0,
        // "transmitPower": 2000000.0,
        volume: true,
        operator: Operators.LEOLABS,
    },

    // TODO: There needs to be a new method for doing FOV when
    // the radar is a fence but not aiming at 90 elevation
    LEOKSR: {
        objName: 'LEOKSR',
        id: 0,
        name: 'Kiwi Space Radar',
        uiName: 'Kiwi Space Radar',
        system: 'S-Band',
        band: 'S-Band',
        type: "PHASED_ARRAY_RADAR",
        lat: -45.03854,
        lon: 170.09556,
        alt: 0.6,
        // obsminaz:  (-13 - 45),
        // obsmaxaz:  (-13 + 45),
        // obsminel:  69,
        // obsmaxel:  71,
        // obsminrange:  100,
        // obsmaxrange:  1800,
        // obsminaz2:  (167 - 45),
        // obsmaxaz2:  (167 + 45),
        // obsminel2:  69,
        // obsmaxel2:  71,
        // obsminrange2:  100,
        // obsmaxrange2:  1800,
        obsminaz: 269,
        obsmaxaz: 271,
        obsminel: 10,
        obsmaxel: 170,
        obsminrange: 100,
        obsmaxrange: 3000,

        changeObjectInterval: 1000,
        url: 'https://platform.leolabs.space/sites/ksr',
        country: 'United States',
        volume: true,
        operator: Operators.LEOLABS,
    },
    LEOCRSR: {
        objName: 'LEOCRSR',
        id: 0,
        name: 'Costa Rica Space Radar',
        uiName: 'Costa Rica SR',
        system: 'S-Band',
        band: 'S-Band',
        type: "PHASED_ARRAY_RADAR",
        lat: 10.611782670733335, // https://www.radartutorial.eu/19.kartei/02.surv/karte087.en.html
        lon: -85.52869380341954,
        alt: 0.0,
        obsminaz: 209,
        obsmaxaz: 211,
        obsminel: 20,
        obsmaxel: 180, // NOTE: Not sure why this looks correct, but 200 goes into the earth
        obsminrange: 100,
        obsmaxrange: 3000,
        obsminaz2: 119,
        obsmaxaz2: 121,
        obsminel2: 20,
        obsmaxel2: 180, // NOTE: Not sure why this looks correct, but 200 goes into the earth
        obsminrange2: 100,
        obsmaxrange2: 3000,

        changeObjectInterval: 1000,
        url: 'https://platform.leolabs.space/sites/crsr',
        country: 'United States',
        volume: true,
        operator: Operators.LEOLABS,
    },
    LEOAZORES: {
        objName: 'LEOAZORES',
        id: 0,
        name: 'Azores Space Radar',
        uiName: 'Azores Space Radar',
        system: 'S-Band',
        band: 'S-Band',
        type: "PHASED_ARRAY_RADAR",
        lat: 36.9975,
        lon: -25.1384933,
        alt: 0.198,
        obsminaz: 209,
        obsmaxaz: 211,
        obsminel: 20,
        obsmaxel: 180, // NOTE: Not sure why this looks correct, but 200 goes into the earth
        obsminrange: 100,
        obsmaxrange: 3000,
        obsminaz2: 119,
        obsmaxaz2: 121,
        obsminel2: 20,
        obsmaxel2: 180, // NOTE: Not sure why this looks correct, but 200 goes into the earth
        obsminrange2: 100,
        obsmaxrange2: 3000,

        changeObjectInterval: 1000,
        url: 'https://platform.leolabs.space/sites/crsr',
        country: 'United States',
        volume: true,
        operator: Operators.LEOLABS,
    },
    LEOWASR: {
        objName: 'LEOWASR',
        id: 0,
        name: 'Western Australia Space Radar',
        uiName: 'Western Australia Space Radar',
        system: 'S-Band',
        band: 'S-Band',
        type: "PHASED_ARRAY_RADAR",
        lat: -33.308487,
        lon: 116.030608,
        alt: 0.241,
        obsminaz: 119,
        obsmaxaz: 121,
        obsminel: 10,
        obsmaxel: 170, // NOTE: Not sure why this looks correct, but 200 goes into the earth
        obsminrange: 100,
        obsmaxrange: 3000,

        changeObjectInterval: 1000,
        url: 'https://platform.leolabs.space/sites/crsr',
        country: 'United States',
        volume: true,
        operator: Operators.LEOLABS,
    },
    // LEO LABS ARSR on hold as of 2023-11-12 due to national security concerns from Argentina

    // //////////////////////
    // ESOC RADARS
    // //////////////////////
    GRV: {
        objName: 'GRV',
        id: 0,
        name: 'Grand Réseau Adapté à la Veille Spatiale',
        uiName: 'Dijon',
        system: 'GRAVES',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 47.347778,
        lon: 5.51638,
        alt: 0.0,
        obsminaz: 90,
        obsmaxaz: 270,
        obsminel: 20,
        obsmaxel: 40,
        obsminrange: 0,
        obsmaxrange: 1700, // http://emits.sso.esa.int/emits-doc/AO5059RD1.pdf

        changeObjectInterval: 20000,
        url: '',
        country: 'France',
        volume: true,
        operator: Operators.ESA,
    },
    TIR: {
        objName: 'TIR',
        id: 0,
        name: 'Wachtberg',
        uiName: 'Wachtberg',
        system: 'TIRA',
        band: 'L/Ku-Band',
        type: "MECHANICAL",
        lat: 50.6166,
        lon: 7.1296,
        alt: 0.0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 1.5, // http://www.issfd.org/ISSFD_2012/ISSFD23_CRSD2_3.pdf
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 2000, // http://emits.sso.esa.int/emits-doc/AO5059RD1.pdf

        changeObjectInterval: 20000,
        url: '',
        country: 'Germany',
        operator: Operators.ESA,
    },
    GES: {
        objName: 'GES',
        id: 0,
        name: 'Schmidtenhöhe',
        uiName: 'Schmidtenhöhe',
        system: 'GESTRA',
        band: 'L-Band',
        type: "MECHANICAL",
        lat: 50.335711,
        lon: 7.6359085,
        alt: 0.0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 1.5,
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 3000,

        changeObjectInterval: 20000,
        url: '',
        country: 'Germany',
        operator: Operators.ESA,
    },
    NRC: {
        objName: 'NRC',
        id: 0,
        name: 'Northern Cross Radiotelescope',
        uiName: 'Medicina',
        system: 'BIRALES',
        band: 'UHF',
        type: "BISTATIC_RADIO_TELESCOPE",
        lat: 44.5208,
        lon: 11.6469,
        alt: 0.025,
        obsminaz: 89.1,
        obsmaxaz: 90.9,
        obsminel: 45,
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 1700,
        obsminaz2: 179.1,
        obsmaxaz2: 180.9,
        obsminel2: 45,
        obsmaxel2: 90,
        obsminrange2: 0,
        obsmaxrange2: 1700,

        changeObjectInterval: 20000,
        url: '',
        country: 'Italy',
        operator: Operators.ESA,
    },
    PDM: {
        objName: 'PDM',
        id: 0,
        name: 'Pratica di Mare Air Base',
        uiName: 'Pratica di Mare',
        system: 'MiTE',
        type: "OPTICAL",
        lat: 41.654444, // https://en.wikipedia.org/wiki/Pratica_di_Mare_Air_Base
        lon: 12.445,
        alt: 0.0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 5, // 0 seems low - https://amostech.com/TechnicalPapers/2015/Adaptive_Optics_Imaging/DelGenio.pdf
        obsmaxel: 90,
        obsminrange: 0, // https://amostech.com/TechnicalPapers/2015/Adaptive_Optics_Imaging/DelGenio.pdf
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        url: '',
        country: 'Italy',
        operator: Operators.ITAF,
    },
    TRO: {
        objName: 'TRO',
        id: 0,
        name: 'Royal Air Force Troödos',
        uiName: 'Royal Air Force Troödos',
        system: 'Starbrook',
        type: "OPTICAL",
        lat: 34.912778,
        lon: 32.883889,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 3,
        obsmaxel: 90,
        obsminrange: 15000,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        url: '',
        country: 'United Kingdom',
        operator: Operators.UKSA,
    },
    Tenerife: {
        objName: 'SDT',
        id: 0,
        name: 'ESA Space Debris Telescope',
        uiName: 'Tenerife',
        system: 'SDT',
        type: "OPTICAL",
        lat: 28.3,
        lon: -16.5097,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 10,
        obsmaxel: 90,
        obsminrange: 15000,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        url: '',
        country: 'Spain',
        operator: Operators.ESA,
    },
    ZimLAT: {
        objName: 'ZimLAT',
        id: 0,
        name: 'Zimmerwald Observatory',
        uiName: 'Zimmerwald',
        system: 'ZimLAT',
        type: "OPTICAL",
        lat: 46.877225,
        lon: 7.465225,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 10,
        obsmaxel: 90,
        obsminrange: 15000,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        url: '',
        country: 'Switzerland',
        operator: Operators.ESA,
    },
    ZimSMART: {
        objName: 'ZimSMART',
        id: 0,
        name: 'Zimmerwald Observatory',
        uiName: 'Zimmerwald',
        system: 'ZimSMART',
        type: "OPTICAL",
        lat: 46.876947,
        lon: 7.465086,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 10,
        obsmaxel: 90,
        obsminrange: 15000,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        url: '',
        country: 'Switzerland',
        operator: Operators.ESA,
    },
    Tromso: {
        objName: 'Tromso',
        id: 0,
        name: 'Tromso',
        uiName: 'Tromso',
        system: 'Incoherent Scatter',
        band: 'UHF/VHF',
        type: "BISTATIC_RADIO_TELESCOPE",
        lat: 69.586439,
        lon: 19.226111,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 30, // https://www.eiscat.se/groups/Operations/ops-manual/ops-manual.htm
        obsmaxel: 90,
        obsminrange: 500,
        obsmaxrange: 1500,

        changeObjectInterval: 20000,
        url: '',
        country: 'Norway',
        operator: Operators.EISCAT,
    },
    Kiruna: {
        objName: 'Kiruna',
        id: 0,
        name: 'Kiruna',
        uiName: 'Kiruna',
        system: 'Incoherent Scatter',
        band: 'UHF/VHF',
        type: "BISTATIC_RADIO_TELESCOPE",
        lat: 67.860778,
        lon: 20.433806,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 10,
        obsmaxel: 90,
        obsminrange: 500,
        obsmaxrange: 1500,

        changeObjectInterval: 20000,
        url: '',
        country: 'Sweden',
        operator: Operators.EISCAT,
    },
    Sodankyla: {
        objName: 'Sodankyla',
        id: 0,
        name: 'Sodankyla',
        uiName: 'Sodankyla',
        system: 'Incoherent Scatter',
        band: 'UHF/VHF',
        type: "BISTATIC_RADIO_TELESCOPE",
        lat: 67.363903,
        lon: 26.630417,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 10,
        obsmaxel: 90,
        obsminrange: 500,
        obsmaxrange: 1500,

        changeObjectInterval: 20000,
        url: '',
        country: 'Finland',
        operator: Operators.EISCAT,
    },
    Svalbard: {
        objName: 'Svalbard',
        id: 0,
        name: 'Svalbard',
        uiName: 'Svalbard',
        system: 'Incoherent Scatter',
        band: 'UHF/VHF',
        type: "BISTATIC_RADIO_TELESCOPE",
        lat: 78.152669,
        lon: 16.058706,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 10,
        obsmaxel: 90,
        obsminrange: 500,
        obsmaxrange: 1500,

        changeObjectInterval: 20000,
        url: '',
        country: 'Norway',
        operator: Operators.EISCAT,
    },
    // ////////////////////////////////////////////////////////////////////////////////////////////////
    // RUSSIAN RADARS
    // ////////////////////////////////////////////////////////////////////////////////////////////////
    OLED: {
        objName: 'OLED',
        id: 0,
        name: 'Olenegorsk',
        uiName: 'Olenegorsk',
        system: 'Dnepr',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 68.1141,
        lon: 33.9102,
        alt: 0.0,
        obsminaz: 280, // All Information via russianforces.org
        obsmaxaz: 340,
        obsminel: 5.5,
        obsmaxel: 34.5,
        obsminrange: 250,
        obsmaxrange: 4600,

        changeObjectInterval: 1000,
        country: 'Russia',
        operator: Operators.RUSSF,
    },
    OLEV: {
        objName: 'OLEV',
        id: 0,
        name: 'Olenegorsk',
        uiName: 'Olenegorsk',
        system: 'Voronezh-VP', // AKA Voronezh-M
        band: 'VHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 68.090694,
        lon: 34.327539,
        alt: 0.0,
        obsminaz: 250, // All Information via russianforces.org
        obsmaxaz: 10,
        obsminel: 7,
        obsmaxel: 70,
        obsminrange: 250,
        obsmaxrange: 6000, // 6000 horizontal, 10000 vertical

        changeObjectInterval: 1000,
        country: 'Russia',
        operator: Operators.RUSSF,
        // Under Contstruction
    },
    PEC: {
        objName: 'PEC',
        id: 0,
        name: 'Pechora',
        uiName: 'Pechora',
        system: `Dar'yal`,
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 65.21,
        lon: 57.295,
        alt: 0.0,
        obsminaz: 305, // All Information via russianforces.org
        obsmaxaz: 55,
        obsminel: 2,
        obsmaxel: 55,
        obsminrange: 300,
        obsmaxrange: 7200,

        changeObjectInterval: 1000,
        country: 'Russia',
        operator: Operators.RUSSF,
    },
    // Vorkuta
    MISD: {
        objName: 'MISD',
        id: 0,
        name: 'Mishelevka',
        uiName: 'Mishelevka',
        system: 'Dnepr',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 52.8555,
        lon: 103.2317,
        alt: 0.0,
        obsminaz: 41, // All Information via russianforces.org
        obsmaxaz: 219,
        obsminel: 5.5,
        obsmaxel: 34.5,
        obsminrange: 250,
        obsmaxrange: 4600,

        changeObjectInterval: 1000,
        country: 'Russia',
        operator: Operators.RUSSF,
    },
    MISV: {
        // NOTE: There are two co-located here
        objName: 'MISV',
        id: 0,
        name: 'Mishelevka',
        uiName: 'Mishelevka',
        system: 'Voronezh-VP', // AKA Voronezh-M or Voronezh-SM
        band: 'VHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 52.8555,
        lon: 103.2317,
        alt: 0.0,
        // boresight 130
        obsminaz: 10, // All Information via russianforces.org
        obsmaxaz: 250,
        obsminel: 2,
        obsmaxel: 70,
        obsminrange: 250,
        obsmaxrange: 6000, // 6000 horizontal, 10000 vertical

        changeObjectInterval: 1000,
        country: 'Russia',
        operator: Operators.RUSSF,
    },
    LEKV: {
        objName: 'LEKV',
        id: 0,
        name: 'Lekhtusi',
        uiName: 'Lekhtusi',
        system: 'Voronezh-M',
        band: 'VHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 60.275458,
        lon: 30.546017,
        alt: 0.0,
        obsminaz: 245,
        obsmaxaz: 355,
        obsminel: 2,
        obsmaxel: 70,
        obsminrange: 250,
        obsmaxrange: 6000,

        changeObjectInterval: 1000,
        country: 'Russia',
        operator: Operators.RUSSF,
    },
    // Planned Voronezh-SM (Ragozinka-2)
    ARMV: {
        objName: 'ARMV',
        id: 0,
        name: 'Armavir',
        uiName: 'Armavir',
        system: 'Voronezh-DM',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 44.925106,
        lon: 40.983894,
        alt: 0.0,
        // 2 Radars = 240az
        obsminaz: 55, // All Information via russianforces.org
        obsmaxaz: 295,
        obsminel: 2,
        obsmaxel: 70,
        obsminrange: 250,
        obsmaxrange: 6000,
        changeObjectInterval: 1000,
        country: 'Russia',

        operator: Operators.RUSSF,
    },
    // Decommissioned???
    // GAN: {
    //   objName: 'GAN',
    //   id: 0,
    //   name: 'Gantsevichi',
    //   uiName: 'GAN',
    //   system: 'GAN',
    //   type: "PHASED_ARRAY_RADAR",
    //   lat:  52.85,
    //   lon:  26.48,
    //   alt:  0.0,
    //   obsminaz:  190, // All Information via russianforces.org
    //   obsmaxaz:  310,
    //   obsminel:  3,
    //   obsmaxel:  80,
    //   obsminrange:  300,
    //   obsmaxrange:  6500,
    //    
    //   changeObjectInterval:  1000,
    //   country: 'Russia',
    //   operator: Operators.RUSSF,
    // },
    KALV: {
        objName: 'KALV',
        id: 0,
        name: 'Kaliningrad', // Pionersky/Kaliningrad
        uiName: 'Kaliningrad',
        system: 'Voronezh-DM', // AKA Voronezh-M
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 54.857294,
        lon: 20.18235,
        alt: 0.0,
        // boresight 240
        obsminaz: 180, // All Information via russianforces.org
        obsmaxaz: 300,
        obsminel: 2,
        obsmaxel: 70,
        obsminrange: 250,
        obsmaxrange: 6000,

        changeObjectInterval: 1000,
        country: 'Russia',
        operator: Operators.RUSSF,
    },
    BARV: {
        objName: 'BARV',
        id: 0,
        name: 'Barnaul',
        uiName: 'Barnaul',
        system: 'Voronezh-DM', // AKA Voronezh-M
        band: 'VHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 53.139194,
        lon: 83.68125,
        alt: 0.0,
        obsminaz: 110, // All Information via russianforces.org
        obsmaxaz: 230,
        obsminel: 2,
        obsmaxel: 70,
        obsminrange: 250,
        obsmaxrange: 6000,

        changeObjectInterval: 1000,
        country: 'Russia',
        operator: Operators.RUSSF,
    },
    YENV: {
        objName: 'YENV',
        id: 0,
        name: 'Yeniseysk',
        uiName: 'Yeniseysk',
        system: 'Voronezh-DM', // AKA Voronezh-M
        band: 'VHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 58.506095,
        lon: 92.046072,
        alt: 0.0,
        // boresight 240
        obsminaz: 330, // All Information via russianforces.org
        obsmaxaz: 90,
        obsminel: 2,
        obsmaxel: 70,
        obsminrange: 250,
        obsmaxrange: 6000,

        changeObjectInterval: 1000,
        country: 'Russia',
        operator: Operators.RUSSF,
    },
    ORSV: {
        objName: 'ORSV',
        id: 0,
        name: 'Orsk',
        uiName: 'Orsk',
        system: 'Voronezh-M',
        band: 'UHF',
        type: "PHASED_ARRAY_RADAR",
        lat: 51.273346,
        lon: 58.95903,
        alt: 0.0,
        // boresight 180 - https://www.janes.com/images/default-source/news-images/bsp_13855-idr-16436.jpg?sfvrsn=aa8c7163_2
        obsminaz: 120, // All Information via russianforces.org
        obsmaxaz: 240,
        obsminel: 2,
        obsmaxel: 70,
        obsminrange: 250,
        obsmaxrange: 6000,

        changeObjectInterval: 1000,
        country: 'Russia',
        operator: Operators.RUSSF,
    },
    // Removed from combat alert in 2020
    // BAL: {
    //   objName: 'BAL',
    //   id: 0,
    //   name: 'Balkhash',
    //   uiName: 'BAL',
    //   system: 'Dnepr',
    //   band: 'UHF',
    //   type: "PHASED_ARRAY_RADAR",
    //   lat:  46.603076,
    //   lon:  74.530985,
    //   alt:  0.0,
    //   obsminaz:  91, // All Information via russianforces.org
    //   obsmaxaz:  151,
    //   obsminel:  5.5,
    //   obsmaxel:  34.5,
    //   obsminrange:  385,
    //   obsmaxrange:  4600,
    //    
    //   changeObjectInterval:  1000,
    //   country: 'Russia',
    //   operator: Operators.RUSSF,
    // },
    STO: {
        objName: 'STO',
        id: 0,
        name: 'Storozhevaya',
        uiName: 'Storozhevaya',
        system: 'Krona',
        band: 'UHF/VHF',
        type: "PHASED_ARRAY_RADAR", // Actually two sites and the other is a telescope/LIDAR combo
        lat: 43.718331,
        lon: 41.226253,
        alt: 2.115,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 5,
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        country: 'Russia',
        operator: Operators.RUSSF,
    },
    NAK: {
        objName: 'NAK',
        id: 0,
        name: 'Nakhodka',
        uiName: 'Nakhodka',
        system: 'Krona-N', // crown of a tree (because of the antenna shape)
        band: 'UHF/VHF',
        type: "PHASED_ARRAY_RADAR", // 1xUHF & 5xSHF radar
        lat: 42.9357,
        lon: 132.576769,
        alt: 0.21,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 2,
        obsmaxel: 90,
        obsminrange: 0,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        country: 'Russia',
        operator: Operators.RUSSF,
    },
    // ////////////////////////////////////////////////////////////////////////////////////////////////
    // CHINESE RADARS
    // ////////////////////////////////////////////////////////////////////////////////////////////////
    // XUA: { // Not operational anymore
    //   id: 0,
    //   name: 'Xuanhua',
    //   shortName: 'XUA',
    //   type: "PHASED_ARRAY_RADAR",
    //   lat:  40.446944,
    //   lon:  115.116389,
    //   alt:  1.6,
    //   obsminaz:  300, // Information via global ssa sensors amos 2010.pdf (sinodefence.com/special/airdefense/project640.asp)
    //   obsmaxaz:  60, // Information via global ssa sensors amos 2010.pdf (sinodefence.com/special/airdefense/project640.asp)
    //   obsminel:  2, // Information via globalsecurity.org
    //   obsmaxel:  80, // Information via globalsecurity.org
    //   obsminrange:  300,
    //   obsmaxrange:  3000, // Information via global ssa sensors amos 2010.pdf (sinodefence.com/special/airdefense/project640.asp)
    //    
    //   changeObjectInterval:  1000,
    //   country: 'China',
    //
    //
    // },
    XIN: {
        objName: 'XIN',
        id: 0,
        name: 'Korla Site Xingjiang', // Korla
        uiName: 'Korla',
        system: 'LPAR',
        type: "PHASED_ARRAY_RADAR",
        lat: 41.64131987863126, // https://hfasia.blogspot.com/2017/02/blog-post_50.html
        lon: 86.23695312232473,
        alt: 0.993, // https://www.freemaptools.com/elevation-finder.htm
        obsminaz: 0, // https://www.globalsecurity.org/space/world/china/images/xinjiang-radar-image-2018-1-s.jpg
        obsmaxaz: 360, // It is on a rotatable platform
        obsminel: 3, // Assumed same characteristics as AN/FPS-115
        obsmaxel: 85,
        obsminrange: 200, // Assumed same characteristics as AN/FPS-115
        obsmaxrange: 5556, // Assumed same characteristics as AN/FPS-115

        changeObjectInterval: 1000,
        country: 'China',
        operator: Operators.PLA,
    },
    HEI: {
        objName: 'HEI',
        id: 0,
        name: 'Huanan Heilongjiang',
        uiName: 'Huanan',
        system: 'LPAR',
        band: 'X-Band',
        type: "PHASED_ARRAY_RADAR", // https://www.globalsecurity.org/wmd/world/china/lpar-x.htm
        lat: 46.528164,
        lon: 130.755235,
        alt: 0.241, // https://www.freemaptools.com/elevation-finder.htm
        obsminaz: 135, // X-Band https://www.globalsecurity.org/wmd/world/china/lpar-x.htm
        obsmaxaz: 225, // Assumed +/- 45 degrees
        obsminel: 3,
        obsmaxel: 65,
        obsminrange: 200,
        obsmaxrange: 3000,

        changeObjectInterval: 1000,
        country: 'China',
        operator: Operators.PLA,
    },
    ZHE: {
        objName: 'ZHE',
        id: 0,
        name: `Lin'an Zhejiang, China`,
        uiName: `Lin'an`,
        system: 'LPAR',
        band: 'X-Band',
        type: "PHASED_ARRAY_RADAR",
        lat: 30.28661248844618, // https://hfasia.blogspot.com/2017/02/blog-post_50.html
        lon: 119.12859385017512,
        alt: 1.342, // https://www.freemaptools.com/elevation-finder.htm
        obsminaz: 60,
        obsmaxaz: 300,
        obsminel: 2,
        obsmaxel: 80,
        obsminrange: 300,
        obsmaxrange: 3000,

        changeObjectInterval: 1000,
        country: 'China',
        operator: Operators.PLA,
    },
    SHD: {
        objName: 'SHD',
        id: 0,
        name: 'Shandong', // P-Band (225 Mhz - 390 Mhz)
        uiName: 'Shandong',
        system: 'LPAR',
        band: 'P-Band',
        type: "PHASED_ARRAY_RADAR", // https://www.globalsecurity.org/wmd/world/china/lpar-p.htm
        lat: 36.023072,
        lon: 118.093115,
        alt: 0.694, // https://www.freemaptools.com/elevation-finder.htm
        obsminaz: 343.9, // Two Faces Boresight ~163.9 and ~103.9 degrees
        // https://www.omnicalculator.com/other/azimuth (163.9 degrees if aimed at Taipei)
        obsmaxaz: 223.9, // https://www.defensenews.com/global/asia-pacific/2022/04/18/new-chinese-radar-looks-towards-japan-satellite-image-shows/
        obsminel: 3,
        obsmaxel: 85,
        obsminrange: 200,
        obsmaxrange: 5500, // ~10,000 Transceivers

        changeObjectInterval: 1000,
        country: 'China',
        operator: Operators.PLA,
    },
    PMO: {
        objName: 'PMO',
        id: 0,
        name: 'Purple Mountain Observatory',
        uiName: 'Nanjing',
        system: '60-cm Zeiss Telescope',
        type: "OPTICAL",
        lat: 32.064946,
        lon: 118.829677,
        alt: 0.267,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 10,
        obsmaxel: 90,
        obsminrange: 15000,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        country: 'China',
        operator: Operators.CAS,
    },
    // ////////////////////////////////////////////////////////////////////////////////////////////////
    // OTHER SENSORS
    // ////////////////////////////////////////////////////////////////////////////////////////////////
    MLS: {
        objName: 'MLS',
        id: 0,
        name: 'Mount Lemmon Survey',
        uiName: 'Tucson',
        system: '1.52 m Telescope',
        type: "OPTICAL",
        lat: 32.442,
        lon: -110.789,
        alt: 2.791,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 10,
        obsmaxel: 90,
        obsminrange: 15000,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        country: 'United States',
        operator: Operators.COMMERCIAL,
    },
    PO: {
        objName: 'PO',
        id: 0,
        name: 'Palomar Mountain Observatory',
        uiName: 'Palomar Observatory',
        system: 'Hale Telescope',
        type: "OPTICAL",
        lat: 33.3564,
        lon: -116.865,
        alt: 1.712,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 10,
        obsmaxel: 90,
        obsminrange: 15000,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        country: 'United States',
        operator: Operators.CALTECH,
    },
    LSO: {
        objName: 'LSO',
        id: 0,
        name: 'La Sagra Observatory',
        uiName: 'La Sagra',
        system: '4x Telescopes',
        type: "OPTICAL",
        lat: 37.9839,
        lon: -2.5644,
        alt: 0,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 10,
        obsmaxel: 90,
        obsminrange: 15000,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        country: 'Spain',
        operator: Operators.ESA,
    },

    // ISON Sensors
    MAY: {
        objName: 'MAY',
        id: 0,
        name: 'Remote Astronomical Society Observatory',
        uiName: 'Mayhill',
        system: 'MPC H06 Telescope',
        type: "OPTICAL",
        lat: 32.9039,
        lon: -105.5289,
        alt: 2.225,
        obsminaz: 0,
        obsmaxaz: 360,
        obsminel: 10,
        obsmaxel: 90,
        obsminrange: 15000,
        obsmaxrange: 200000,

        changeObjectInterval: 20000,
        country: 'United States',
        operator: Operators.COMMERCIAL,
    },
    ROC: {
        objName: 'ROC',
        id: 0,
        name: 'Leshan',
        uiName: 'Leshan',
        system: 'AN/FPS-115 (SRP)',
        type: "PHASED_ARRAY_RADAR",
        lat: 24.499,
        lon: 121.072,
        alt: 2.6, // https://taiwanenglishnews.com/tag/leshan-radar-station/ (2.6km)
        obsminaz: 0, // Appears to be 3 faced
        obsmaxaz: 360, // https://www.google.com/maps/place/24%C2%B029'45.6%22N+121%C2%B004'15.6%22E/@24.4985462,121.0709751,154m/data=!3m1!1e3!4m5!3m4!1s0x0:0xe0073e890dc05d63!8m2!3d24.496!4d121.071
        obsminel: -1, // "Tracks surface ships" https://www.globalsecurity.org/military/world/taiwan/air-defense-over.htm
        obsmaxel: 85,
        obsminrange: 200,
        obsmaxrange: 5556,
        changeObjectInterval: 1000,
        url: 'https://fas.org/man/eprint/leshan.pdf',
        country: 'Taiwan',
        operator: Operators.ROC,
    },
};