// automatically generated by the FlatBuffers compiler, do not modify
export var SensorType;
(function (SensorType) {
    /**
     * Basic or undefined sensor type
     */
    SensorType[SensorType["UNKNOWN"] = 0] = "UNKNOWN";
    /**
     * General optical sensors
     */
    SensorType[SensorType["OPTICAL"] = 1] = "OPTICAL";
    /**
     * Detects infrared radiation
     */
    SensorType[SensorType["INFRARED_SENSOR"] = 2] = "INFRARED_SENSOR";
    /**
     * Sensitive to ultraviolet light
     */
    SensorType[SensorType["ULTRAVIOLET_SENSOR"] = 3] = "ULTRAVIOLET_SENSOR";
    /**
     * For X-ray detection
     */
    SensorType[SensorType["X_RAY_SENSOR"] = 4] = "X_RAY_SENSOR";
    /**
     * For gamma-ray detection
     */
    SensorType[SensorType["GAMMA_RAY_SENSOR"] = 5] = "GAMMA_RAY_SENSOR";
    /**
     * Basic radar systems
     */
    SensorType[SensorType["RADAR"] = 6] = "RADAR";
    /**
     * Advanced radar with phased array technology
     */
    SensorType[SensorType["PHASED_ARRAY_RADAR"] = 7] = "PHASED_ARRAY_RADAR";
    /**
     * For high-resolution imaging
     */
    SensorType[SensorType["SYNTHETIC_APERTURE_RADAR"] = 8] = "SYNTHETIC_APERTURE_RADAR";
    /**
     * For astronomical observations using bistatic setup
     */
    SensorType[SensorType["BISTATIC_RADIO_TELESCOPE"] = 9] = "BISTATIC_RADIO_TELESCOPE";
    /**
     * For radio astronomy
     */
    SensorType[SensorType["RADIO_TELESCOPE"] = 10] = "RADIO_TELESCOPE";
    /**
     * For atmospheric studies
     */
    SensorType[SensorType["ATMOSPHERIC_SENSOR"] = 11] = "ATMOSPHERIC_SENSOR";
    /**
     * For observing space weather phenomena
     */
    SensorType[SensorType["SPACE_WEATHER_SENSOR"] = 12] = "SPACE_WEATHER_SENSOR";
    /**
     * General environmental monitoring
     */
    SensorType[SensorType["ENVIRONMENTAL_SENSOR"] = 13] = "ENVIRONMENTAL_SENSOR";
    /**
     * For measuring seismic activities
     */
    SensorType[SensorType["SEISMIC_SENSOR"] = 14] = "SEISMIC_SENSOR";
    /**
     * For gravity measurements
     */
    SensorType[SensorType["GRAVIMETRIC_SENSOR"] = 15] = "GRAVIMETRIC_SENSOR";
    /**
     * For magnetic field detection
     */
    SensorType[SensorType["MAGNETIC_SENSOR"] = 16] = "MAGNETIC_SENSOR";
    /**
     * For electromagnetic field analysis
     */
    SensorType[SensorType["ELECTROMAGNETIC_SENSOR"] = 17] = "ELECTROMAGNETIC_SENSOR";
    /**
     * For temperature and heat detection
     */
    SensorType[SensorType["THERMAL_SENSOR"] = 18] = "THERMAL_SENSOR";
    /**
     * For detecting chemicals and substances
     */
    SensorType[SensorType["CHEMICAL_SENSOR"] = 19] = "CHEMICAL_SENSOR";
    /**
     * For biological research and detection
     */
    SensorType[SensorType["BIOLOGICAL_SENSOR"] = 20] = "BIOLOGICAL_SENSOR";
    /**
     * For detecting ionizing radiation
     */
    SensorType[SensorType["RADIATION_SENSOR"] = 21] = "RADIATION_SENSOR";
    /**
     * For detecting subatomic particles
     */
    SensorType[SensorType["PARTICLE_DETECTOR"] = 22] = "PARTICLE_DETECTOR";
    /**
     * Light Detection and Ranging
     */
    SensorType[SensorType["LIDAR"] = 23] = "LIDAR";
    /**
     * Sound Navigation and Ranging
     */
    SensorType[SensorType["SONAR"] = 24] = "SONAR";
    /**
     * General telescopes for astronomical observations
     */
    SensorType[SensorType["TELESCOPE"] = 25] = "TELESCOPE";
    /**
     * For spectral analysis
     */
    SensorType[SensorType["SPECTROSCOPIC_SENSOR"] = 26] = "SPECTROSCOPIC_SENSOR";
    /**
     * For measuring light intensity
     */
    SensorType[SensorType["PHOTOMETRIC_SENSOR"] = 27] = "PHOTOMETRIC_SENSOR";
    /**
     * For analyzing polarization of light
     */
    SensorType[SensorType["POLARIMETRIC_SENSOR"] = 28] = "POLARIMETRIC_SENSOR";
    /**
     * For detailed imaging using interference
     */
    SensorType[SensorType["INTERFEROMETRIC_SENSOR"] = 29] = "INTERFEROMETRIC_SENSOR";
    /**
     * Capturing image data at multiple wavelengths
     */
    SensorType[SensorType["MULTISPECTRAL_SENSOR"] = 30] = "MULTISPECTRAL_SENSOR";
    /**
     * Advanced imaging across many spectral bands
     */
    SensorType[SensorType["HYPERSPECTRAL_SENSOR"] = 31] = "HYPERSPECTRAL_SENSOR";
    /**
     * For Global Positioning System reception
     */
    SensorType[SensorType["GPS_RECEIVER"] = 32] = "GPS_RECEIVER";
    /**
     * For tracking satellites
     */
    SensorType[SensorType["SATELLITE_TRACKING_SENSOR"] = 33] = "SATELLITE_TRACKING_SENSOR";
})(SensorType || (SensorType = {}));
